package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.utils.pilotAutoBuilder.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Forward Backward Tuning Auto
 */
@Autonomous(name = "Forward Backward Tuning Auto", group = "Pilot")
public class ForwardBackwardTuningAuto extends PilotAutoBase {
    public ForwardBackwardTuningAuto() {
        super("Forward_Backward_Tuning_Auto");
    }
}
