package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.brainstemPilotAuto.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Heading Tuning
 */
@Autonomous(name = "Heading Tuning", group = "Pilot")
public class HeadingTuningAuto extends PilotAutoBase {
    public HeadingTuningAuto() {
        super("Heading_Tuning");
    }
}
