package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.utils.pilotAutoBuilder.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Nine Ball (123)
 */
@Autonomous(name = "Nine Ball (123)", group = "Pilot")
public class NineBall123Auto extends PilotAutoBase {
    public NineBall123Auto() {
        super("Nine_Ball_(123)");
    }
}
