package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.utils.pilotAutoBuilder.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Spline Tuning Auto
 */
@Autonomous(name = "Spline Tuning Auto", group = "Pilot")
public class SplineTuningAuto extends PilotAutoBase {
    public SplineTuningAuto() {
        super("Spline_Tuning_Auto");
    }
}
