package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.brainstemPilotAuto.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Tolerance Tuning
 */
@Autonomous(name = "Tolerance Tuning", group = "Pilot")
public class ToleranceTuningAuto extends PilotAutoBase {
    public ToleranceTuningAuto() {
        super("Tolerance_Tuning");
    }
}
