package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.utils.pilotAutoBuilder.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Tuning Auto
 */
@Autonomous(name = "Tuning Auto", group = "Pilot")
public class TuningAuto extends PilotAutoBase {
    public TuningAuto() {
        super("Tuning_Auto");
    }
}
