package org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.utils.pilotAutoBuilder.PilotAutoBase;

/**
 * AUTO-GENERATED by Brainstem Pilot UI — do not edit manually.
 * Variant: Twelve Ball (123)
 */
@Autonomous(name = "Twelve Ball (123)", group = "Pilot")
public class TwelveBall123Auto extends PilotAutoBase {
    public TwelveBall123Auto() {
        super("Twelve_Ball_(123)");
    }
}
